base_cfg: cfg/mnist/common.yaml
clustering: CKMFS
ae:
  encoder:
    - 1024
    - 512
    - 256
  decoder:
    - 256
    - 512
    - 1024
stg:
  sigma: 0.5
  reg_lamba: 0.1
  hidden_dim: 64
  start_reg_after_epoch: 500
  lr: 5e-1

