dataset: MNIST

data_dir: D:/data/mode_seeking/mnist_tcr
input_dim: 784
n_clusters: 2
batch_size: 1024
lr: .2
wd: 1e-6
repitions: 10

tau_min: 100
tau_max: 100
tau_sched: exponential

activation: tanh
init_weights: true

trainer:
  gpus: 1
  auto_select_gpus: True
  max_epochs: 500
  progress_bar_refresh_rate: 10
  deterministic: True
  logger: True
  log_every_n_steps: 10
  check_val_every_n_epoch: 10