dataset: MNIST

data_dir: D:/data/mode_seeking/mnist_tcr
input_dim: 784
n_clusters: 10
batch_size: 256
lr: 1e-3
ae_pretrain_epochs: 10
repitions: 1

tau_min: 1e-3
tau_max: 1e3
tau_sched: exponential

trainer:
  gpus: 1
  auto_select_gpus: True
  max_epochs: 1000
  progress_bar_refresh_rate: 20
  deterministic: True
  logger: True
  log_every_n_steps: 10
  check_val_every_n_epoch: 10